services:
    php:
        build:
            context: .
            dockerfile: docker/Dockerfile
        volumes:
            - ./:/var/www
            - ./docker/php.ini:/usr/local/etc/php/conf.d/custom.ini
        depends_on:
            - mysql
        environment:
            - APP_ENV=local
        networks:
            - docker-project
#        extra_hosts:
#            - 'host.docker.internal:host-gateway'
#        ports:
#            - '${APP_PORT:-8080}:80'
#            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'

    nginx:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
        networks:
            - docker-project

    mysql:
        image: mysql:latest
        environment:
            MYSQL_DATABASE: ${DB_DATABASE:-laravel}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD-laravel}
            MYSQL_USER: ${DB_USERNAME-laravel}
            MYSQL_PASSWORD: ${DB_PASSWORD-laravel}
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - docker-project

    mailpit:
        image: axllent/mailpit:latest
        ports:
            - "8025:8025"
        networks:
            - docker-project

volumes:
    db_data:

networks:
    docker-project:
